services:
  helios-db:
    container_name: helios-db
    image: postgres:latest 
    ports:
      - "5100:5432"
    environment:
      POSTGRES_DB: helios
      POSTGRES_USER: phaeton
      POSTGRES_PASSWORD: ecliptic
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./user-sql-scripts/user-tables-creation.sql:/docker-entrypoint-initdb.d/user-tables-creation.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U phaeton -d helios"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: {}
